### ISSUE TITLE
project database corrupted: file size does not match stored value

### ISSUE THREAD

**Issue by agrieve** [pantsbuild/jmake#22]
Recently started making use of jmake inside of chromium, but we are occasionally hitting this error message:

```
bin/jmake -pdb gen/content/shell/android/content_shell_apk_java__compile_java.initial.jar.pdb -C-g -C-encoding -CUTF-8 -classpath lib.java/content/shell/android/content_shell_java.interface.jar:lib.java/base/base_java.interface.jar:lib.java/content/public/android/content_java.interface.jar:lib.java/media/base/android/media_java.interface.jar:lib.java/net/android/net_java.interface.jar:lib.java/ui/android/ui_java.interface.jar -C-sourcepath -C -bootclasspath lib.java/android.interface.jar -C-source -C1.7 -C-target -C1.7 -C-Xlint:unchecked -C-Xlint:deprecation -d /tmp/tmp8CxgKR/classes ../../content/shell/android/shell_apk/src/org/chromium/content_shell_apk/ContentShellApplication.java ../../content/shell/android/shell_apk/src/org/chromium/content_shell_apk/ContentShellActivity.java /tmp/tmp8CxgKR/java/org/chromium/content_shell_apk/R.java )
jmake: project database corrupted: file size does not match stored value
```

I sadly cannot provide reliable repro steps, but wanted to at least file a bug to track this. Relevant Chromium bug: https://code.google.com/p/chromium/issues/detail?id=551449

**Comment by jsirois** [comment]
It may not be clear, but we forked just to provide a home for our patches.  We only maintain jmake for use by pantsbuild/pants, and we now in fact have moved on to using zinc for both our scala and java incremental compiles.

This is all to say that this issue won't get love in this home.  I will say though that the pants devs are all intrigued that you're using jmake!

**Comment by ericzundel** [comment]
Just some more feedback here - pants only ever used the text version of the pdb format. If you want to submit a patch, I'll be happy to merge it in for you and cut a release, but we aren't using this codebase any more.

**Comment by jsirois** [comment]
To be a bit more helpful, our fork baseline info is here: https://github.com/pantsbuild/jmake/blob/master/README.pantsbuild

You're of course welcome to fork this repo if you want to hack on jmake in the confines of github.

**Comment by agrieve** [comment]
Yes! We've gotten by without incremental compiles for Chromium so far, and jmake seemed like a nice drop-in way of enabling them. Hadn't seen zinc in all the searches I'd done so far though, so I'll see if that works any better. Thanks!
